name: React CI/CD

# Define when this workflow will run
on:
  pull_request:
    branches: [main] # Runs on PRs targeting main
  push:
    branches: [main] # Runs when code is pushed to main

jobs:
  # Main job that handles building and testing
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Step 4: Verify the build
      - name: Build
        run: npm run build

  # Job for production deployment checks
  production-deploy:
    needs: build-and-test # This job only runs after build-and-test succeeds
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Production deployment
        run: |
          echo "Vercel will handle the production deployment automatically via GitHub integration"
          # The actual deployment happens through Vercel's GitHub integration
